QT.KWaylandClient.VERSION = 5.54.0
QT.KWaylandClient.MAJOR_VERSION = 5
QT.KWaylandClient.MINOR_VERSION = 54
QT.KWaylandClient.PATCH_VERSION = 0
QT.KWaylandClient.name = KF5WaylandClient
QT.KWaylandClient.defines = 
QT.KWaylandClient.includes = $$QT_MODULE_INCLUDE_BASE/KF5
QT.KWaylandClient.private_includes =
QT.KWaylandClient.libs = $$QT_MODULE_LIB_BASE
QT.KWaylandClient.depends = core
